<?php
$namespace      = isset($this->namespace) ?  $this->namespace : null;
$flashMessenger = $this->flashMessenger()->getPluginFlashMessenger();

if ($namespace) {
    $flashMessenger->setNamespace($namespace);
}
?>

<?php if ($flashMessenger->hasCurrentMessages()) :?>
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <?php echo $this->htmlList($flashMessenger->getCurrentMessages(), false, array('class' => 'list-unstyled'))?>
    </div>
<?php endif?>


<?php if ($flashMessenger->hasCurrentInfoMessages()) :?>
    <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <?php echo $this->htmlList($flashMessenger->getCurrentInfoMessages(), false, array('class' => 'list-unstyled'))?>
    </div>
<?php endif?>

<?php if ($flashMessenger->hasCurrentSuccessMessages()) :?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <?php echo $this->htmlList($flashMessenger->getCurrentSuccessMessages(), false, array('class' => 'list-unstyled'))?>
    </div>
<?php endif?>


<?php if ($flashMessenger->hasCurrentErrorMessages()) :?>
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <?php echo $this->htmlList($flashMessenger->getCurrentErrorMessages(), false, array('class' => 'list-unstyled'))?>
    </div>
<?php endif?>

