<?php
$namespace      = isset($this->namespace) ? $this->namespace : null;
$flashMessenger = $this->flashMessenger();

if ($namespace) {
    $flashMessenger->getPluginFlashMessenger()->setNamespace($namespace);
}

$flashMessenger->setMessageOpenFormat('<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <ul class="list-unstyled"><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

echo $flashMessenger->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
echo $flashMessenger->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
echo $flashMessenger->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success'));
